[project]
name = "gpt"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.4.2",
    "huggingface-hub>=1.3.1",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
]
